language: go

go:
  - 1.6
  - 1.7.x

install:
  - export PATH=$PATH:$HOME/gopath/bin
  - go get github.com/tools/godep
  - godep restore

script:
  - cd ${TRAVIS_BUILD_DIR}/examples && go run test.go

